name: EKS-With-Terraform Deployment Delete

# on:
#   push:
#     branches:
#       - main
on: workflow_dispatch

env:
 # verbosity setting for Terraform logs--test
 TF_LOG: INFO
 # Credentials for deployment to AWS
 aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
 aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 # S3 bucket for the Terraform state
 BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }} 

jobs:
  delete_iam_stack:
    name: "Delete IAM Stack"
    runs-on: ubuntu-latest
    needs: [delete_eks_stack]
    defaults:
     run:
       shell: bash       
       working-directory: ./terraform/iam
    
    steps:
    - name: Checkout the repository to the runner
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Test configuration of AWS CLI
      run: |
        aws --version
        aws configure list | grep region | awk '{print $2}'

    - name: Setup Terraform with specified version on the runner
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.5

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format Check
      run: terraform fmt -check=true

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Destroy
      id: destroy
      run: terraform destroy -var-file=../environments/dev/iam.tfvars -auto-approve -no-color -input=false
      continue-on-error: true
  delete_network_stack:
    name: "Delete Network Stack"
    runs-on: ubuntu-latest
    needs: [delete_eks_stack,delete_bastion_host_stack]
    defaults:
     run:
       shell: bash       
       working-directory: ./terraform/infra-deployments/deploy-network
    
    steps:
    - name: Checkout the repository to the runner
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Test configuration of AWS CLI
      run: |
        aws --version
        aws configure list | grep region | awk '{print $2}'

    - name: Setup Terraform with specified version on the runner
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.5

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format Check
      run: terraform fmt -check=true

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Destroy
      id: destroy
      run: terraform destroy -var-file=../../environments/dev/deploy-network.tfvars -auto-approve -no-color -input=false
      continue-on-error: true 
  delete_eks_stack:
    name: "Delete EKS Cluster"
    runs-on: ubuntu-latest
    needs: [delete_app_stack]
    defaults:
     run:
       shell: bash       
       working-directory: ./terraform/infra-deployments/deploy-eks
    
    steps:
    - name: Checkout the repository to the runner
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Test configuration of AWS CLI
      run: |
        aws --version
        aws configure list | grep region | awk '{print $2}'

    - name: Setup Terraform with specified version on the runner
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.5

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format Check
      run: terraform fmt -check=true

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Destroy
      id: destroy
      run: terraform destroy -var-file=../../environments/dev/deploy-eks.tfvars -auto-approve -no-color -input=false
      continue-on-error: true      
  delete_bastion_host_stack:
    name: "Delete Bastion-Host"
    runs-on: ubuntu-latest
    defaults:
     run:
       shell: bash       
       working-directory: ./terraform/infra-deployments/deploy-bastion-host
    
    steps:
    - name: Checkout the repository to the runner
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Test configuration of AWS CLI
      run: |
        aws --version
        aws configure list | grep region | awk '{print $2}'

    - name: Setup Terraform with specified version on the runner
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.5

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format Check
      run: terraform fmt -check=true

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Destroy
      id: destroy
      run: terraform destroy -var-file=../../environments/dev/deploy-bastion-host.tfvars -auto-approve -no-color -input=false
      continue-on-error: true     
  delete_app_stack:
    name: "Delete App Stack"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash       
        working-directory: ./terraform/platform-deployments/deploy-app
    
    steps:
    - name: Checkout the repository to the runner
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Test configuration of AWS CLI
      run: |
        aws --version
        aws configure list | grep region | awk '{print $2}'

    - name: Setup Terraform with specified version on the runner
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.5

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format Check
      run: terraform fmt -check=true

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Destroy
      id: destroy
      run: terraform destroy -auto-approve -no-color -input=false
      continue-on-error: true